# Generated by Django 6.0.4 on 2026-04-14 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='仓库名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='仓库编码')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='所在位置')),
                ('manager', models.CharField(blank=True, max_length=64, null=True, verbose_name='负责人')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'db_table': 'inventory_warehouse',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_no', models.CharField(max_length=64, unique=True, verbose_name='盘点单号')),
                ('check_date', models.DateField(verbose_name='盘点日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('completed', '已完成')], default='draft', max_length=16, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='盘点仓库')),
            ],
            options={
                'verbose_name': '库存盘点',
                'verbose_name_plural': '库存盘点',
                'db_table': 'inventory_check',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=128, verbose_name='物料名称')),
                ('spec', models.CharField(blank=True, max_length=128, null=True, verbose_name='规格型号')),
                ('unit', models.CharField(default='件', max_length=32, verbose_name='单位')),
                ('book_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='账面数量')),
                ('actual_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='实盘数量')),
                ('diff_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='差异数量')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('check_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorycheck', verbose_name='盘点单')),
            ],
            options={
                'verbose_name': '盘点明细',
                'verbose_name_plural': '盘点明细',
                'db_table': 'inventory_check_item',
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_no', models.CharField(max_length=64, unique=True, verbose_name='调拨单号')),
                ('transfer_date', models.DateField(verbose_name='调拨日期')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='out_transfers', to='inventory.warehouse', verbose_name='调出仓库')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_transfers', to='inventory.warehouse', verbose_name='调入仓库')),
            ],
            options={
                'verbose_name': '库存调拨',
                'verbose_name_plural': '库存调拨',
                'db_table': 'inventory_stock_transfer',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=128, verbose_name='物料名称')),
                ('spec', models.CharField(blank=True, max_length=128, null=True, verbose_name='规格型号')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='调拨数量')),
                ('unit', models.CharField(default='件', max_length=32, verbose_name='单位')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfer', verbose_name='调拨单')),
            ],
            options={
                'verbose_name': '调拨明细',
                'verbose_name_plural': '调拨明细',
                'db_table': 'inventory_stock_transfer_item',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=128, verbose_name='物料名称')),
                ('spec', models.CharField(blank=True, max_length=128, null=True, verbose_name='规格型号')),
                ('unit', models.CharField(default='件', max_length=32, verbose_name='单位')),
                ('qty', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='库存数量')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'db_table': 'inventory_stock',
                'ordering': ['-id'],
                'unique_together': {('warehouse', 'material_name', 'spec')},
            },
        ),
    ]
