# Generated by Django 6.0.4 on 2026-04-19 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=64, verbose_name='库位编码')),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, verbose_name='条码')),
                ('size', models.CharField(default='小', max_length=32, verbose_name='库位大小')),
                ('product_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='货物编码')),
                ('product_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='货物名称')),
                ('is_empty', models.BooleanField(default=True, verbose_name='是否空位')),
                ('inbound_time', models.DateTimeField(blank=True, null=True, verbose_name='入库时间')),
                ('outbound_barcode', models.CharField(blank=True, max_length=64, null=True, verbose_name='已出库条码')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse', verbose_name='所属仓库')),
            ],
            options={
                'verbose_name': '仓库库位',
                'verbose_name_plural': '仓库库位',
                'db_table': 'inventory_warehouse_location',
                'ordering': ['location_code'],
                'unique_together': {('warehouse', 'location_code')},
            },
        ),
    ]
