# Generated by Django 6.0.4 on 2026-04-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_warehouselocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='物料编码')),
                ('name', models.CharField(max_length=128, verbose_name='物料名称')),
                ('spec', models.CharField(blank=True, max_length=128, null=True, verbose_name='规格型号')),
                ('category', models.CharField(blank=True, max_length=64, null=True, verbose_name='分类')),
                ('unit', models.CharField(default='件', max_length=32, verbose_name='单位')),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, verbose_name='条码')),
                ('status', models.CharField(default='active', max_length=16, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '物料档案',
                'verbose_name_plural': '物料档案',
                'db_table': 'inventory_material',
                'ordering': ['-id'],
            },
        ),
    ]
