# Generated by Django 6.0.4 on 2026-04-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='库存数量'),
        ),
    ]
