# Generated by Django 6.0.4 on 2026-04-19 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_material_qty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='warning_status',
            field=models.CharField(default='normal', max_length=16, verbose_name='预警状态'),
        ),
        migrations.AddField(
            model_name='material',
            name='warning_threshold',
            field=models.DecimalField(decimal_places=4, default=50, max_digits=14, verbose_name='预警阈值'),
        ),
        migrations.CreateModel(
            name='StockWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=128, verbose_name='物料名称')),
                ('current_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='当前数量')),
                ('threshold', models.DecimalField(decimal_places=4, default=50, max_digits=14, verbose_name='预警阈值')),
                ('status', models.CharField(choices=[('warning', '预警'), ('urgent', '紧急')], default='warning', max_length=16, verbose_name='预警级别')),
                ('is_handled', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.material', verbose_name='关联物料')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '库存预警',
                'verbose_name_plural': '库存预警',
                'db_table': 'inventory_stock_warning',
                'ordering': ['-id'],
            },
        ),
    ]
