# Generated by Django 6.0.4 on 2026-04-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_warning_status_material_warning_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockwarning',
            name='warning_type',
            field=models.CharField(choices=[('low_stock', '库存不足'), ('picking_shortage', '拣货缺货')], default='low_stock', max_length=16, verbose_name='预警类型'),
        ),
    ]
