# Generated by Django 6.0.4 on 2026-04-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stockwarning_warning_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockwarning',
            name='material_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='物料编码'),
        ),
    ]
