# Generated by Django 6.0.4 on 2026-04-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockwarning_material_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockwarning',
            name='picking_item_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='关联拣货明细ID'),
        ),
    ]
