# Generated by Django 6.0.4 on 2026-04-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stockwarning_picking_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='large_location',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='大库位'),
        ),
        migrations.AddField(
            model_name='material',
            name='small_location',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='小库位'),
        ),
    ]
