# Generated by Django 6.0.4 on 2026-04-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_material_large_location_material_small_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='small_location',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='小库位'),
        ),
    ]
