# Generated by Django 6.0.4 on 2026-04-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_material_small_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('pending', '待执行'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=16, verbose_name='状态'),
        ),
    ]
