# Generated by Django 6.0.4 on 2026-04-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stocktransfer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockwarning',
            name='spec',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='规格型号'),
        ),
        migrations.AlterField(
            model_name='warehouselocation',
            name='size',
            field=models.CharField(choices=[('小', '小'), ('中', '中'), ('大', '大')], default='小', max_length=32, verbose_name='库位大小'),
        ),
    ]
