# Generated by Django 6.0.4 on 2026-04-14 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=64, unique=True, verbose_name='工号')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=16, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('id_card', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号')),
                ('department', models.CharField(blank=True, max_length=64, null=True, verbose_name='部门')),
                ('position', models.CharField(blank=True, max_length=64, null=True, verbose_name='职位')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('status', models.CharField(choices=[('active', '在职'), ('resigned', '离职'), ('probation', '试用期')], default='active', max_length=16, verbose_name='状态')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '员工档案',
                'verbose_name_plural': '员工档案',
                'db_table': 'hr_employee',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='考勤日期')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='上班时间')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='下班时间')),
                ('status', models.CharField(choices=[('normal', '正常'), ('late', '迟到'), ('early', '早退'), ('absent', '旷工'), ('leave', '请假')], default='normal', max_length=16, verbose_name='考勤状态')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '考勤记录',
                'verbose_name_plural': '考勤记录',
                'db_table': 'hr_attendance',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=64, unique=True, verbose_name='招聘编号')),
                ('position', models.CharField(max_length=128, verbose_name='招聘岗位')),
                ('department', models.CharField(blank=True, max_length=64, null=True, verbose_name='招聘部门')),
                ('headcount', models.IntegerField(default=1, verbose_name='招聘人数')),
                ('status', models.CharField(choices=[('open', '招聘中'), ('closed', '已关闭'), ('filled', '已招满')], default='open', max_length=16, verbose_name='状态')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='岗位要求')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='招聘负责人')),
            ],
            options={
                'verbose_name': '招聘管理',
                'verbose_name_plural': '招聘管理',
                'db_table': 'hr_recruitment',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=7, verbose_name='薪资月份')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='基本工资')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='奖金')),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='扣款')),
                ('total_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='实发工资')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '薪资管理',
                'verbose_name_plural': '薪资管理',
                'db_table': 'hr_salary',
                'ordering': ['-id'],
            },
        ),
    ]
