# Generated by Django 6.0.4 on 2026-04-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='工资卡号'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='开户行'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='合同到期日'),
        ),
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.CharField(blank=True, choices=[('high_school', '高中'), ('college', '大专'), ('bachelor', '本科'), ('master', '硕士'), ('doctor', '博士')], max_length=16, null=True, verbose_name='学历'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='紧急联系人'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='紧急联系电话'),
        ),
        migrations.AddField(
            model_name='employee',
            name='graduate_school',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='毕业院校'),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='试用期结束日'),
        ),
        migrations.AddField(
            model_name='employee',
            name='resignation_date',
            field=models.DateField(blank=True, null=True, verbose_name='离职日期'),
        ),
    ]
