# Generated by Django 6.0.4 on 2026-04-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_bank_account_employee_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-id'], 'verbose_name': '考勤记录', 'verbose_name_plural': '考勤记录'},
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='加班时长(小时)'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='work_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='工作时长(小时)'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
