# Generated by Django 6.0.4 on 2026-04-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_attendance_options_attendance_overtime_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DingTalkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(max_length=64, verbose_name='AppKey')),
                ('app_secret', models.CharField(max_length=255, verbose_name='AppSecret')),
                ('access_token', models.CharField(blank=True, max_length=512, null=True, verbose_name='AccessToken')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '钉钉配置',
                'verbose_name_plural': '钉钉配置',
                'db_table': 'hr_dingtalk_config',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='dingtalk_user_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='钉钉用户ID'),
        ),
    ]
