# Generated by Django 6.0.4 on 2026-04-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_dingtalkconfig_employee_dingtalk_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='base_check_in',
            field=models.TimeField(blank=True, null=True, verbose_name='应上班时间'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='base_check_out',
            field=models.TimeField(blank=True, null=True, verbose_name='应下班时间'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='dingtalk_detail',
            field=models.JSONField(blank=True, null=True, verbose_name='钉钉打卡详情'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='early_minutes',
            field=models.IntegerField(default=0, verbose_name='早退分钟数'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_minutes',
            field=models.IntegerField(default=0, verbose_name='迟到分钟数'),
        ),
    ]
