# Generated by Django 6.0.4 on 2026-04-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_attendance_base_check_in_attendance_base_check_out_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together={('employee', 'year_month')},
        ),
    ]
