# Generated by Django 6.0.4 on 2026-04-22 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.hashers import make_password


def sync_existing_employees(apps, schema_editor):
    """为现有员工自动创建系统用户并建立关联"""
    Employee = apps.get_model('hr', 'Employee')
    User = apps.get_model('system', 'User')
    db_alias = schema_editor.connection.alias

    def generate_username(base_name):
        if not User.objects.using(db_alias).filter(username=base_name).exists():
            return base_name
        seq = 1
        while True:
            candidate = f'{base_name}{seq}'
            if not User.objects.using(db_alias).filter(username=candidate).exists():
                return candidate
            seq += 1

    for emp in Employee.objects.using(db_alias).filter(user__isnull=True):
        username = generate_username(emp.name)
        user = User.objects.using(db_alias).create(
            username=username,
            email=emp.email or '',
            phone=emp.phone or '',
            is_active=emp.status != 'resigned',
            password=make_password(emp.employee_no),
        )
        emp.user = user
        emp.save(using=db_alias, update_fields=['user'])


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_salary_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='系统用户'),
        ),
        migrations.RunPython(sync_existing_employees, reverse_code=migrations.RunPython.noop),
    ]
