# Generated by Django 6.0.4 on 2026-04-24 23:23

import django.db.models.deletion
from django.db import migrations, models


def migrate_employee_data(apps, schema_editor):
    """将 Employee 的 department/position 字符串迁移为外键关联"""
    Employee = apps.get_model('hr', 'Employee')
    Department = apps.get_model('system', 'Department')
    Position = apps.get_model('hr', 'Position')

    # 建立部门名称映射
    dept_map = {d.name: d for d in Department.objects.all()}

    for emp in Employee.objects.all():
        # 备份旧数据
        emp.department_old = emp.department
        emp.position_old = emp.position

        # 映射部门外键
        if emp.department:
            dept = dept_map.get(emp.department)
            if dept:
                emp.department_new = dept
                # 创建/获取职位并映射
                if emp.position:
                    pos, _ = Position.objects.get_or_create(
                        name=emp.position,
                        department=dept,
                        defaults={'sort_order': 0, 'is_active': True}
                    )
                    emp.position_new = pos
        emp.save()


def reverse_migrate(apps, schema_editor):
    """回滚：恢复字符串数据"""
    Employee = apps.get_model('hr', 'Employee')
    for emp in Employee.objects.all():
        if emp.department_old:
            emp.department = emp.department_old
        if emp.position_old:
            emp.position = emp.position_old
        emp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_employee_user'),
        ('system', '0002_menu_add_department'),
    ]

    operations = [
        # 1. 先创建 Position 模型（因为 Employee.position 外键需要它）
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='职位名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='system.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
                'db_table': 'hr_position',
                'ordering': ['sort_order', 'id'],
            },
        ),
        # 2. 添加旧字段备份
        migrations.AddField(
            model_name='employee',
            name='department_old',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='部门(旧)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position_old',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='职位(旧)'),
        ),
        # 3. 添加新的外键字段（使用临时名称）
        migrations.AddField(
            model_name='employee',
            name='department_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_new', to='system.department', verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_new', to='hr.position', verbose_name='职位'),
        ),
        # 4. 数据迁移
        migrations.RunPython(migrate_employee_data, reverse_migrate),
        # 5. 删除旧的 CharField 字段
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        # 6. 重命名新字段为最终名称
        migrations.RenameField(
            model_name='employee',
            old_name='department_new',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='position_new',
            new_name='position',
        ),
    ]
