# Generated by Django 6.0.4 on 2026-04-14 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128, verbose_name='产品名称')),
                ('product_code', models.CharField(max_length=64, unique=True, verbose_name='产品编码')),
                ('version', models.CharField(default='V1.0', max_length=32, verbose_name='版本')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'BOM',
                'verbose_name_plural': 'BOM',
                'db_table': 'production_bom',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=128, verbose_name='物料名称')),
                ('spec', models.CharField(blank=True, max_length=128, null=True, verbose_name='规格型号')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='用量')),
                ('unit', models.CharField(default='件', max_length=32, verbose_name='单位')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.bom', verbose_name='BOM')),
            ],
            options={
                'verbose_name': 'BOM明细',
                'verbose_name_plural': 'BOM明细',
                'db_table': 'production_bom_item',
            },
        ),
        migrations.CreateModel(
            name='MaterialRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_no', models.CharField(max_length=64, unique=True, verbose_name='领料单号')),
                ('requisition_date', models.DateField(verbose_name='领料日期')),
                ('warehouse', models.CharField(default='默认仓库', max_length=64, verbose_name='领料仓库')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='领料人')),
            ],
            options={
                'verbose_name': '领料单',
                'verbose_name_plural': '领料单',
                'db_table': 'production_requisition',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=128, verbose_name='物料名称')),
                ('spec', models.CharField(blank=True, max_length=128, null=True, verbose_name='规格型号')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='领料数量')),
                ('unit', models.CharField(default='件', max_length=32, verbose_name='单位')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.materialrequisition', verbose_name='领料单')),
            ],
            options={
                'verbose_name': '领料明细',
                'verbose_name_plural': '领料明细',
                'db_table': 'production_requisition_item',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=64, unique=True, verbose_name='工单编号')),
                ('order_date', models.DateField(verbose_name='开工日期')),
                ('product_name', models.CharField(max_length=128, verbose_name='产品名称')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='生产数量')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('released', '已下达'), ('processing', '生产中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=16, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.bom', verbose_name='关联BOM')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '生产工单',
                'verbose_name_plural': '生产工单',
                'db_table': 'production_order',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionInStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_no', models.CharField(max_length=64, unique=True, verbose_name='入库单号')),
                ('stock_date', models.DateField(verbose_name='入库日期')),
                ('warehouse', models.CharField(default='默认仓库', max_length=64, verbose_name='入库仓库')),
                ('product_name', models.CharField(max_length=128, verbose_name='产品名称')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='入库数量')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.productionorder', verbose_name='关联工单')),
            ],
            options={
                'verbose_name': '生产入库',
                'verbose_name_plural': '生产入库',
                'db_table': 'production_in_stock',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.productionorder', verbose_name='关联工单'),
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_no', models.CharField(max_length=64, unique=True, verbose_name='计划编号')),
                ('plan_date', models.DateField(verbose_name='计划日期')),
                ('product_name', models.CharField(max_length=128, verbose_name='产品名称')),
                ('product_code', models.CharField(max_length=64, verbose_name='产品编码')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='计划数量')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=16, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('planner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='计划员')),
            ],
            options={
                'verbose_name': '生产计划',
                'verbose_name_plural': '生产计划',
                'db_table': 'production_plan',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='productionorder',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionplan', verbose_name='关联计划'),
        ),
    ]
