# Generated by Django 6.0.4 on 2026-04-19 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_warning_status_material_warning_threshold_and_more'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.material', verbose_name='关联物料'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='单价'),
        ),
    ]
