# Generated by Django 6.0.4 on 2026-04-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_bomitem_material_bomitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='实际完工日期'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='实际开工日期'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='completed_qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='已完工数量'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='priority',
            field=models.CharField(choices=[('urgent', '紧急'), ('high', '高'), ('normal', '普通'), ('low', '低')], default='normal', max_length=16, verbose_name='优先级'),
        ),
    ]
