# Generated by Django 6.0.4 on 2026-04-19 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_productionorder_actual_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplan',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.bom', verbose_name='关联BOM'),
        ),
    ]
