# Generated by Django 6.0.4 on 2026-04-19 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_warning_status_material_warning_threshold_and_more'),
        ('production', '0004_productionplan_bom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequisition',
            name='audit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='issue_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出库时间'),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已审核'), ('issued', '已出库'), ('closed', '已关闭'), ('cancelled', '已取消')], default='draft', max_length=16, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='materialrequisitionitem',
            name='actual_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='实发数量'),
        ),
        migrations.AddField(
            model_name='materialrequisitionitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.material', verbose_name='关联物料'),
        ),
        migrations.AddField(
            model_name='materialrequisitionitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='单价'),
        ),
    ]
