# Generated by Django 6.0.4 on 2026-04-19 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_materialrequisition_audit_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productioninstock',
            name='actual_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='实际入库数量'),
        ),
        migrations.AddField(
            model_name='productioninstock',
            name='audit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='productioninstock',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_instocks', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='productioninstock',
            name='confirm_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='入库确认时间'),
        ),
        migrations.AddField(
            model_name='productioninstock',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已审核'), ('confirmed', '已入库'), ('closed', '已关闭'), ('cancelled', '已取消')], default='draft', max_length=16, verbose_name='状态'),
        ),
    ]
