# Generated by Django 6.0.4 on 2026-04-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='department',
            field=models.CharField(blank=True, help_text='填写部门名称，如：人力资源部、销售部。为空表示通用菜单', max_length=64, null=True, verbose_name='所属部门'),
        ),
    ]
