# Generated by Django 6.0.4 on 2026-04-14 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivablePayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.CharField(max_length=64, unique=True, verbose_name='单据编号')),
                ('doc_type', models.CharField(choices=[('receivable', '应收'), ('payable', '应付')], max_length=16, verbose_name='类型')),
                ('counterparty', models.CharField(max_length=128, verbose_name='往来单位')),
                ('doc_date', models.DateField(verbose_name='单据日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='已结金额')),
                ('status', models.CharField(choices=[('unpaid', '未结清'), ('partial', '部分结清'), ('paid', '已结清')], default='unpaid', max_length=16, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '应收应付',
                'verbose_name_plural': '应收应付',
                'db_table': 'finance_receivable_payable',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AccountSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='科目编码')),
                ('name', models.CharField(max_length=64, verbose_name='科目名称')),
                ('category', models.CharField(choices=[('asset', '资产'), ('liability', '负债'), ('equity', '所有者权益'), ('income', '收入'), ('expense', '费用')], max_length=16, verbose_name='科目类别')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.accountsubject', verbose_name='上级科目')),
            ],
            options={
                'verbose_name': '会计科目',
                'verbose_name_plural': '会计科目',
                'db_table': 'finance_account_subject',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.CharField(max_length=64, unique=True, verbose_name='单据编号')),
                ('doc_type', models.CharField(choices=[('receipt', '收款'), ('payment', '付款')], max_length=16, verbose_name='类型')),
                ('counterparty', models.CharField(max_length=128, verbose_name='往来单位')),
                ('doc_date', models.DateField(verbose_name='日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
            ],
            options={
                'verbose_name': '收付款',
                'verbose_name_plural': '收付款',
                'db_table': 'finance_payment_receipt',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=64, unique=True, verbose_name='凭证号')),
                ('voucher_date', models.DateField(verbose_name='凭证日期')),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='借方合计')),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='贷方合计')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('preparer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='制单人')),
            ],
            options={
                'verbose_name': '记账凭证',
                'verbose_name_plural': '记账凭证',
                'db_table': 'finance_voucher',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VoucherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=255, verbose_name='摘要')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='借方金额')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='贷方金额')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.accountsubject', verbose_name='会计科目')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.voucher', verbose_name='凭证')),
            ],
            options={
                'verbose_name': '凭证明细',
                'verbose_name_plural': '凭证明细',
                'db_table': 'finance_voucher_item',
            },
        ),
    ]
