# Generated by Django 6.0.4 on 2026-04-19 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='bank_account',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='银行账户'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='payment_method',
            field=models.CharField(choices=[('cash', '现金'), ('bank_transfer', '银行转账'), ('check', '支票'), ('wechat', '微信支付'), ('alipay', '支付宝')], default='bank_transfer', max_length=16, verbose_name='付款方式'),
        ),
        migrations.AddField(
            model_name='receivablepayable',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='到期日'),
        ),
        migrations.AddField(
            model_name='receivablepayable',
            name='source_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='来源单号'),
        ),
        migrations.AddField(
            model_name='receivablepayable',
            name='source_type',
            field=models.CharField(choices=[('sales_order', '销售订单'), ('purchase_order', '采购订单'), ('manual', '手工录入')], default='manual', max_length=16, verbose_name='来源类型'),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='核销金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='核销时间')),
                ('payment_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='finance.paymentreceipt', verbose_name='收付款单')),
                ('receivable_payable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='finance.receivablepayable', verbose_name='应收应付单')),
            ],
            options={
                'verbose_name': '核销明细',
                'verbose_name_plural': '核销明细',
                'db_table': 'finance_settlement',
                'ordering': ['-id'],
            },
        ),
    ]
