# Generated by Django 6.0.4 on 2026-04-19 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_paymentreceipt_bank_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucheritem',
            options={'ordering': ['line_no'], 'verbose_name': '凭证明细', 'verbose_name_plural': '凭证明细'},
        ),
        migrations.AddField(
            model_name='voucher',
            name='attachment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='附件URL'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='audit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核日期'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('audited', '已审核'), ('cancelled', '已作废')], default='draft', max_length=16, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='line_no',
            field=models.PositiveIntegerField(default=1, verbose_name='行号'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='preparer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='制单人'),
        ),
    ]
