# Generated by Django 6.0.4 on 2026-04-20 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_voucheritem_options_voucher_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='单位名称')),
                ('type', models.CharField(choices=[('customer', '客户'), ('supplier', '供应商'), ('both', '客户+供应商'), ('other', '其他')], default='customer', max_length=16, verbose_name='单位类型')),
                ('contact', models.CharField(blank=True, max_length=64, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('bank_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='开户银行')),
                ('bank_account', models.CharField(blank=True, max_length=64, null=True, verbose_name='银行账号')),
                ('tax_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='税号')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '往来单位',
                'verbose_name_plural': '往来单位',
                'db_table': 'finance_counterparty',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='counterparty_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.counterparty', verbose_name='往来单位关联'),
        ),
        migrations.AddField(
            model_name='receivablepayable',
            name='counterparty_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivables', to='finance.counterparty', verbose_name='往来单位关联'),
        ),
    ]
