# Generated by Django 6.0.4 on 2026-04-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_counterparty_paymentreceipt_counterparty_obj_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='settlement',
            unique_together={('payment_receipt', 'receivable_payable')},
        ),
    ]
