# Generated by Django 6.0.4 on 2026-04-14 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='供应商名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='供应商编码')),
                ('contact', models.CharField(blank=True, max_length=64, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'purchase_supplier',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_no', models.CharField(max_length=64, unique=True, verbose_name='入库单号')),
                ('stock_date', models.DateField(verbose_name='入库日期')),
                ('warehouse', models.CharField(default='默认仓库', max_length=64, verbose_name='入库仓库')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '采购入库',
                'verbose_name_plural': '采购入库',
                'db_table': 'purchase_in_stock',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=128, verbose_name='物料名称')),
                ('spec', models.CharField(blank=True, max_length=128, null=True, verbose_name='规格型号')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='入库数量')),
                ('unit', models.CharField(default='件', max_length=32, verbose_name='单位')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaseinstock', verbose_name='入库单')),
            ],
            options={
                'verbose_name': '采购入库明细',
                'verbose_name_plural': '采购入库明细',
                'db_table': 'purchase_in_stock_item',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=64, unique=True, verbose_name='订单编号')),
                ('order_date', models.DateField(verbose_name='订单日期')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='交货日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('partial', '部分入库'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=16, verbose_name='状态')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='总金额')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('purchaser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='采购员')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '采购订单',
                'verbose_name_plural': '采购订单',
                'db_table': 'purchase_order',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='purchaseinstock',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.purchaseorder', verbose_name='关联采购订单'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=128, verbose_name='物料名称')),
                ('spec', models.CharField(blank=True, max_length=128, null=True, verbose_name='规格型号')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='采购数量')),
                ('unit', models.CharField(default='件', max_length=32, verbose_name='单位')),
                ('price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='单价')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='金额')),
                ('received_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='已入库数量')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaseorder', verbose_name='采购订单')),
            ],
            options={
                'verbose_name': '采购订单明细',
                'verbose_name_plural': '采购订单明细',
                'db_table': 'purchase_order_item',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(max_length=64, unique=True, verbose_name='申请单号')),
                ('request_date', models.DateField(verbose_name='申请日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回'), ('ordered', '已转单')], default='draft', max_length=16, verbose_name='状态')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='总金额')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '采购申请',
                'verbose_name_plural': '采购申请',
                'db_table': 'purchase_request',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=128, verbose_name='物料名称')),
                ('spec', models.CharField(blank=True, max_length=128, null=True, verbose_name='规格型号')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='数量')),
                ('unit', models.CharField(default='件', max_length=32, verbose_name='单位')),
                ('estimated_price', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='预估单价')),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='预估金额')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaserequest', verbose_name='申请单')),
            ],
            options={
                'verbose_name': '采购申请明细',
                'verbose_name_plural': '采购申请明细',
                'db_table': 'purchase_request_item',
            },
        ),
    ]
