# Generated by Django 6.0.4 on 2026-04-14 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='客户名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='客户编码')),
                ('contact', models.CharField(blank=True, max_length=64, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'sales_customer',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=64, unique=True, verbose_name='订单编号')),
                ('order_date', models.DateField(verbose_name='订单日期')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='交货日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('partial', '部分出库'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=16, verbose_name='状态')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='总金额')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer', verbose_name='客户')),
                ('salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='销售员')),
            ],
            options={
                'verbose_name': '销售订单',
                'verbose_name_plural': '销售订单',
                'db_table': 'sales_order',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=128, verbose_name='物料名称')),
                ('spec', models.CharField(blank=True, max_length=128, null=True, verbose_name='规格型号')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='销售数量')),
                ('unit', models.CharField(default='件', max_length=32, verbose_name='单位')),
                ('price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='单价')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='金额')),
                ('delivered_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='已出库数量')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder', verbose_name='销售订单')),
            ],
            options={
                'verbose_name': '销售订单明细',
                'verbose_name_plural': '销售订单明细',
                'db_table': 'sales_order_item',
            },
        ),
        migrations.CreateModel(
            name='SalesOutStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_no', models.CharField(max_length=64, unique=True, verbose_name='出库单号')),
                ('stock_date', models.DateField(verbose_name='出库日期')),
                ('warehouse', models.CharField(default='默认仓库', max_length=64, verbose_name='出库仓库')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesorder', verbose_name='关联销售订单')),
            ],
            options={
                'verbose_name': '销售出库',
                'verbose_name_plural': '销售出库',
                'db_table': 'sales_out_stock',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOutStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=128, verbose_name='物料名称')),
                ('spec', models.CharField(blank=True, max_length=128, null=True, verbose_name='规格型号')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='出库数量')),
                ('unit', models.CharField(default='件', max_length=32, verbose_name='单位')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesoutstock', verbose_name='出库单')),
            ],
            options={
                'verbose_name': '销售出库明细',
                'verbose_name_plural': '销售出库明细',
                'db_table': 'sales_out_stock_item',
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(max_length=64, unique=True, verbose_name='退货单号')),
                ('return_date', models.DateField(verbose_name='退货日期')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='退货总金额')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer', verbose_name='客户')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '销售退货',
                'verbose_name_plural': '销售退货',
                'db_table': 'sales_return',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=128, verbose_name='物料名称')),
                ('spec', models.CharField(blank=True, max_length=128, null=True, verbose_name='规格型号')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='退货数量')),
                ('unit', models.CharField(default='件', max_length=32, verbose_name='单位')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='单价')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='金额')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesreturn', verbose_name='退货单')),
            ],
            options={
                'verbose_name': '销售退货明细',
                'verbose_name_plural': '销售退货明细',
                'db_table': 'sales_return_item',
            },
        ),
    ]
