# Generated by Django 6.0.4 on 2026-04-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='银行信息'),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='信用额度'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='所属行业'),
        ),
        migrations.AddField(
            model_name='customer',
            name='level',
            field=models.CharField(choices=[('A', 'A级-VIP'), ('B', 'B级-重要'), ('C', 'C级-普通'), ('D', 'D级-潜在')], default='C', max_length=8, verbose_name='客户等级'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_no',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='统一社会信用代码'),
        ),
    ]
