# Generated by Django 6.0.4 on 2026-04-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_customer_bank_info_customer_credit_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='order_no',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='订单编号'),
        ),
    ]
