# Generated by Django 6.0.4 on 2026-04-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_salesorder_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='allow_partial_shipment',
            field=models.BooleanField(default=False, verbose_name='允许部分出货'),
        ),
    ]
