# Generated by Django 6.0.4 on 2026-04-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_customer_allow_partial_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='material_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='物料编码'),
        ),
    ]
