# Generated by Django 6.0.4 on 2026-04-22 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesorderitem_material_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPickingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picking_no', models.CharField(blank=True, max_length=64, unique=True, verbose_name='拣货单号')),
                ('status', models.CharField(choices=[('pending', '待指派'), ('assigned', '已指派'), ('accepted', '已接单'), ('picking', '拿货中'), ('complete', '齐发待出库'), ('shortage', '欠发待出库'), ('done', '已完成'), ('cancelled', '已取消')], default='pending', max_length=16, verbose_name='状态')),
                ('warehouse', models.CharField(default='默认仓库', max_length=64, verbose_name='仓库')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickings', to=settings.AUTH_USER_MODEL, verbose_name='指派员工')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picking_lists', to='sales.salesorder', verbose_name='关联销售订单')),
                ('picker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_pickings', to=settings.AUTH_USER_MODEL, verbose_name='实际拿货人')),
            ],
            options={
                'verbose_name': '销售拣货单',
                'verbose_name_plural': '销售拣货单',
                'db_table': 'sales_picking_list',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesPickingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='物料编码')),
                ('material_name', models.CharField(max_length=128, verbose_name='物料名称')),
                ('spec', models.CharField(blank=True, max_length=128, null=True, verbose_name='规格型号')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='需拿数量')),
                ('unit', models.CharField(default='件', max_length=32, verbose_name='单位')),
                ('location_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='库位号')),
                ('picked_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='实际拿到数量')),
                ('shortage_qty', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='缺货数量')),
                ('status', models.CharField(choices=[('pending', '待拿'), ('picked', '已拿'), ('shortage', '缺货')], default='pending', max_length=16, verbose_name='状态')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品图片')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesorderitem', verbose_name='关联订单明细')),
                ('picking_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salespickinglist', verbose_name='拣货单')),
            ],
            options={
                'verbose_name': '拣货明细',
                'verbose_name_plural': '拣货明细',
                'db_table': 'sales_picking_list_item',
                'ordering': ['id'],
            },
        ),
    ]
