# Generated by Django 6.0.4 on 2026-04-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salespickinglist_salespickinglistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespickinglistitem',
            name='refunded_qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='退款数量'),
        ),
        migrations.AlterField(
            model_name='salespickinglistitem',
            name='status',
            field=models.CharField(choices=[('pending', '待拿'), ('picked', '已拿'), ('shortage', '缺货'), ('refunded', '已退款')], default='pending', max_length=16, verbose_name='状态'),
        ),
    ]
